### ISSUE TITLE
Timer for limiting versioning is not working properly

### ISSUE THREAD

**Issue by emirhanozlen** [hunterbeanland/AutoVer#5]
I set 1 min 1 sec for each versioning but app still creates backups whenever the file(s) are changed

**Comment by Hard-Wired** [comment]
I believe the setting you are referring to is intended to be the full sync check interval. Think of it as the minimum interval AutoVer makes sure everything is in sync. AutoVer's primary purpose seems to be designed to back up changes to files as they happen, which is why it is perfect for people who make changes to files they may have to revert back to frequently. This feature has saved my bacon several times now (no pun intended, but now that I typed it I like it).

**Comment by hunterbeanland** [comment]
no, it is suppose to limit the versioning. Unable to replicate on the next version
